config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'welcome/index'
    resources :users do
    resources :reminders
  end
  
    root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/deleteaccount' => 'users#destroy'
  post '/users' => 'users#create'
  put '/update' => 'users#update'
end

app/models/reminder.rb
class Reminder < ApplicationRecord
    belongs_to :user, :class_name => "User"
    validates :title, presence: true, length: { minimum: 5 }
    validates :date, presence: true
    validates :time, presence: true
    validates :notes, presence: true, length: { minimum: 10 } 
    after_create :remind
    def remind 
        @isTest=self.user.email=='test@test.com'
        if self.user.phone_notifications
        @twilio_number = '+13365609193'
        account_sid = @isTest ? ENV['TWILIO_TEST_SID'] : ENV['TWILIO_SID']
         @client = Twilio::REST::Client.new account_sid, @isTest ? ENV['TWILIO_TEST_TOKEN'] : ENV['TWILIO_TOKEN'] 
         time_str = ((self.time).localtime).strftime("%I:%M%p on %b. %d, %Y")
          reminder_body = 'Reminder for ' + self.user.name + "\r\n\n" + 
                "Title: " + self.title + "\r\n\n" + 
                "Notes: " + self.notes + "\r\n\n" +
                "Date: " + self.date.strftime("%b %d %Y") + "\r\n\n" + 
    		    "Time:" + self.time.strftime("%l:%M %P") +  "\r\n\n"
          message = @client.api.account(account_sid).messages.create(
                 :from => @twilio_number,
                 :to => self.user.phone,
                 :body => reminder_body
                     )
         end
               if self.user.email_notifications
                from = Email.new(email: 'test@example.com')
                to = Email.new(email: self.user.email)
                subject = 'Reminder for ' + self.user.name
                emailText = "Title: " + self.title + "\r\n\n" +
    			        "Date: " + self.date.strftime("%b %d %Y") + "\r\n\n" + 
    		        	"Time:" + self.time.strftime("%l:%M %P") +  "\r\n\n" +
                        "Notes: " + self.notes
                content = Content.new(type: 'text/plain', value: emailText)
                mail = Mail.new(from, subject, to, content)
                sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
                response = sg.client.mail._('send').post(request_body: mail.to_json)
            end
    end
    
    def when_to_run
         minutes_before_appointment = 5.minutes
         reminder_time = self.time
         reminder_time - minutes_before_appointment
    end
  handle_asynchronously :remind, :run_at => Proc.new { |i| i.when_to_run }
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
require 'sendgrid-ruby'
require 'date'
require 'rubygems'
require 'twilio-ruby'
include SendGrid
    
    def new
        @reminder = Reminder.new
        @user=current_user
    end
    
    def create
        @user=current_user
        @isTest=@user.email=='test@test.com'
        @reminder = current_user.reminders.new(reminder_params)
        if @reminder.save
        #     if @user.email_notifications
        #         from = Email.new(email: 'test@example.com')
        #         to = Email.new(email: @user.email)
        #         subject = 'Reminder for ' + @user.name
        #         emailText = "Title: " + @reminder.title + "\r\n\n" +
    			 #       "Date: " + @reminder.date.strftime("%b %d %Y") + "\r\n\n" + 
    		  #      	"Time:" + @reminder.time.strftime("%l:%M %P") +  "\r\n\n" +
        #                 "Notes: " + @reminder.notes
        #         content = Content.new(type: 'text/plain', value: emailText)
        #         mail = Mail.new(from, subject, to, content)
        #         sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
        #         response = sg.client.mail._('send').post(request_body: mail.to_json)
        #         puts response.status_code
        #         puts response.body
        #         puts response.headers
        #     end
        #     if @user.phone_notifications
                
        #         @client = Twilio::REST::Client.new(@isTest ? ENV['TWILIO_TEST_SID'] : ENV['TWILIO_SID'], @isTest ? ENV['TWILIO_TEST_TOKEN'] : ENV['TWILIO_TOKEN'])
        #         message = @client.messages.create(
        #                          from: @isTest ? '+15005550006' : '+13365609193',
        #                          body: 'Reminder for ' + @user.name + "\r\n\n" + 
        #         "Title: " + @reminder.title + "\r\n\n" + 
        #         "Notes: " + @reminder.notes + "\r\n\n" +
        #         "Date: " + @reminder.date.strftime("%b %d %Y") + "\r\n\n" + 
    		  #  "Time:" + @reminder.time.strftime("%l:%M %P") +  "\r\n\n",
        #                          to: @user.phone
        #                       )
        #     end
         redirect_to user_reminder_path(@user, @reminder)
            
        else
            render 'new'
        end
    end
    
    def show
        @user=current_user
        @reminder = Reminder.find(params[:id])
    end
    def index
       
        @reminders = current_user.reminders
        
        @user=current_user
    end
    
    def edit
        @user=current_user
        @reminder = Reminder.find(params[:id])
    end
    
    def update
        @user=current_user
        @reminder = Reminder.find(params[:id])
        
        if @reminder.update(reminder_params)
            redirect_to user_reminder_path(@user, @reminder)
        else
            render 'edit'
        end
    end
    
    def destroy
        @user=current_user
        @reminder = Reminder.find(params[:id])
        
        @reminder.destroy
        
        redirect_to user_reminders_path(@user)
    end
end

private
def reminder_params
    params.require(:reminder).permit(:title, :date, :time, :notes)
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= form_for [@user, @reminder] do |f| %>
 
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reminder.errors.count, "error") %> prohibited
        this reminder from being saved:
      </h2>
      <ul>
        <% @reminder.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title, 'Title your reminder' %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :date, 'Enter a date' %>
    <%= f.date_field :date %>
  </p>
  
   <p>
    <%= f.label :time, 'Set a time' %>
    <%= f.time_field :time %>
  </p>
 
  <p>
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>
 
<%= render 'form' %>

<%= link_to 'Back', user_reminders_path(@user) %>

app/views/reminders/index.html.erb
<h1>List Reminders</h1>

<%= link_to 'New Reminder', new_user_reminder_path,  id: 'back5' %><br><br><br><br>
<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Time</th>
    <th>Notes</th>
  </tr>
 
  <% @reminders.each do |reminder| %>
    <tr>
      <td><%= reminder.title %></td>
      <td><%= reminder.date %></td>
      <td><%= reminder.time %></td>
      <td><%= reminder.notes %></td>
      <td><%= link_to 'Show', user_reminder_path(@user, reminder) %></td>
      <td><%= link_to 'Edit', edit_user_reminder_path(@user, reminder) %></td>
      <td>
          <%= link_to 'Destroy',
             user_reminder_path(@user, reminder),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this reminder?' } 
            %>
      </td>
    </tr>
  <% end %>
</table>
<br><%= link_to 'Back', '/welcome/index',  id: 'back2' %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', user_reminders_path(@user), id: 'back1' %>

app/views/reminders/show.html.erb
<p>
    <strong> Title: </strong>
    <%= @reminder.title %>
</p>
<p>
    <strong> Date: </strong>
    <%= @reminder.date.strftime("%b" + ". " + "%d %Y") %>
</p>
<p>
    <strong> Time: </strong>
    <%= @reminder.time.strftime("%l:%M %P") %>
</p>
<p>
    <strong> Notes: </strong>
    <%= @reminder.notes %>
</p>

<%= link_to 'List of Reminders', user_reminders_path(@user)%>