config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'welcome/index'
    resources :users do
    resources :reminders
  end
  
    root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/deleteaccount' => 'users#destroy'
  post '/users' => 'users#create'
  put '/update' => 'users#update'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
    if @user 
      
    else 
      redirect_to '/login'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Welcome to the SMS Reminder App</h1><br><br>
<%#= link_to 'Reminder List', controller: 'reminders' %>
<div id="buttons">
<%= link_to 'New Reminder', new_user_reminder_path(@user), id: 'mainbutton1'%><br><br><br><br>
<%= link_to 'List of Reminders', user_reminders_path(@user), id: 'mainbutton2'%><br><br><br><br>
<%= link_to 'My Account', user_path(@user), id: 'mainbutton3'%>
</div> 
</p>

app/views/welcome/login.html.erb
<h1>Login</h1
<%= form_for :user do |f| %>
  <p>
    <%= f.label :email, 'Email Address' %>
    <%= f.string :email %>
  </p>
  
  <p>
    <%= f.label :password, 'Password' %>
    <%= f.string :password %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/signup.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Email: <%= f.string :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>